### ISSUE TITLE
Adding a paragraph after an image requires extra line for proper markdown formatting

### ISSUE THREAD

**Issue by robertdevore** [ryanwelcher/vscode-readme-editor#4]
I ran into an issue where if I try to add a paragraph after an image, it shows the text on the same line as the image in the markdown.

So I need to add an extra blank line after the image in order for the next paragraph to show up underneath the image.

[Video Example](https://cln.sh/msDSRLtwxqszbMLfJgcP)

**Comment by ryanwelcher** [comment]
Thanks for submitting this! I believe this is an issue in the library being used to output the markdown. I have created a PR it [here.](https://github.com/dmsnell/blocky-formats/pull/5)

**Comment by ryanwelcher** [comment]
@robertdevore my PR was merged into the repo we're consuming. Mind testing this and seeing if it fixes the issue?

**Comment by robertdevore** [comment]
@ryanwelcher Yup, working great now thank you 🤘

**Comment by ryanwelcher** [comment]
Closing as fixed.
